//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_SW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int branch_id { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    }
}
